apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcade-deploy
  labels:
    app: arcade
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: arcade
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: arcade
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: ghcr.io/hungryengineer/the-weekender/arcade-app-image:34
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
              protocol: TCP
          