apiVersion: v1
kind: Service
metadata:
  name: arcade-svc
  labels:
    app: arcade
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    app: arcade
