trigger:
- azure-pipelines

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: Build and publish stage
  jobs:
  - job: Build
    displayName: Build job
    # pool:
    #   name: '<YOUR_AGENT_POOL_NAME>'
    
    steps:

    - script: docker login -u $(gpr_user) -p $(gpr_pat) docker.pkg.github.com
      displayName: Logging into GitHub Package Registry
      
    - script: docker build -t docker.pkg.github.com/$(Build.Repository.ID)/octocat-generator:$(Build.BuildNumber) .
      displayName: Building Docker image
      
    - script: |-
        curl -s -H "Authorization: Token $(gpr_pat)" -H "Accept: application/json" -H "Content-type: application/json" -X POST -d "{ \"ref\": \"refs/tags/$(Build.BuildNumber)\", \"sha\": \"$(Build.SourceVersion)\"}" https://api.github.com/repos/$(Build.Repository.ID)/git/refs
      displayName: Create tag

    - script: docker push docker.pkg.github.com/$(Build.Repository.ID)/octocat-generator:$(Build.BuildNumber)
      displayName: Pushing Docker image to GitHub Package Repository
