name: 'Terraform deployment'

on:
  push:
    branches: [ "pre-master" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: playground

    defaults:
      run:
        shell: bash

    steps:
    - name: Set up environment variables
      run: |
          echo "AWS_ACCESS_KEY_ID=your-access-key-id" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=your-secret-access-key" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=your-default-region" >> $GITHUB_ENV
    
    # Repo checkout
    - name: Checkout
      uses: actions/checkout@v3

    # Install Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      # with:
      #   cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # Terraform init
    - name: Terraform Init
      run: terraform init ../../env/network

    # Terraform Format
    - name: Terraform Format
      run: terraform fmt -check ../../env/network

    # Terraform plan
    - name: Terraform Plan
      run: terraform plan -input=false ../../env/network
    
    # Terraform apply
    - name: Terraform Apply
      if: github.ref == 'refs/heads/"pre-master"' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false ../../env/network