name: 'Arcade Application deployment'

on:  
  push:
    branches: [ "pre-master" ]

permissions: write-all  
    # contents: write
    # pull-requests: write
    # repository-projects: write 

jobs:
    build-and-publish-latest: 
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/pre-master' # Running this job only for pre-master branch

        steps:
        - uses: actions/checkout@v2 # Checking out the repo 

        - name: Build and Publish latest Docker image
          uses: DrSkunk/gp-docker-action@1.1.9
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
            image-name: arcade-app-image # Provide only Docker image name, tag will be automatically set to latest
            dockerfile: ./devsecops_x_arcade_game/Application/snake_game/Dockerfile
            image-tag: ${{github.run_number}}

    # deploy:
    #     runs-on: ubuntu-latest
    #     needs: [build-and-publish-latest]

    #     steps:
    #     - uses: actions/checkout@v2 

    #     - name: AWS Credentials 
    #       uses: aws-actions/configure-aws-credentials@v1
    #       with:
    #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #         aws-region: ap-south-1  # change as needed

    #     - name: helm deploy
    #       uses: koslibpro/helm-eks-action@master
    #       env:
    #         KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
    #         with:
    #         command: helm upgrade --install arcaderelease file:./devsecops_x_arcade_game/Application/arcade-helm -f .values.yaml --set image.tag=${{ github.run_number }} --wait